# name: Scrape Instagram

# on:
#   schedule:
#     - cron: "0 * * * *"  # every hour
#   workflow_dispatch:

# jobs:
#   scrape:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.11"

#       - name: Install dependencies
#         run: |
#           pip install selenium psycopg2-binary cloudinary requests

#       - name: Download Chrome & ChromeDriver
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y chromium-browser
#           wget https://chromedriver.storage.googleapis.com/135.0.1/chromedriver_linux64.zip
#           unzip chromedriver-linux64.zip
#           sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
#           sudo chmod +x /usr/local/bin/chromedriver

#       - name: Run script
#         run: python insta2.py
